id: 891c5509-bf2d-4d18-8f6a-ccc1c43b7b66
version: 36
name: ThreatGridTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3a462079-516f-47ad-81e4-1fd3077f7481
    type: start
    task:
      id: 3a462079-516f-47ad-81e4-1fd3077f7481
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e1fc9d2a-dd77-4a8a-89f0-9ea9fa38c307
    type: regular
    task:
      id: e1fc9d2a-dd77-4a8a-89f0-9ea9fa38c307
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: f6f618c6-8e5b-47ae-87c4-ad4fb6fa6c6e
    type: regular
    task:
      id: f6f618c6-8e5b-47ae-87c4-ad4fb6fa6c6e
      version: -1
      name: Get user information from current session
      description: Get logged in user
      script: Threat Grid New|||threat-grid-who-am-i
      type: regular
      iscommand: true
      brand: Threat Grid New
    nexttasks:
      '#none#':
      - "4"
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 8b84f11e-205e-42d4-8796-48905fab68f2
    type: regular
    task:
      id: 8b84f11e-205e-42d4-8796-48905fab68f2
      version: -1
      name: Get samples (limit of 1) from given time range
      description: Search samples on the Threat Grid platform. Input parameters are
        ANDed together. Only finished samples can be searched (that is, the ones that
        are having a status of succ or fail.)
      script: Threat Grid New|||threat-grid-get-samples
      type: regular
      iscommand: true
      brand: Threat Grid New
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      after:
        simple: 2018-07-01T00:00:00-0000
      before:
        simple: 2018-09-10T00:00:00-0000
      id: {}
      ids: {}
      ioc: {}
      limit:
        simple: "1"
      md5: {}
      offset: {}
      org_only: {}
      sha1: {}
      sha256: {}
      user_only: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
  "4":
    id: "4"
    taskid: cd560420-a769-4cbf-83c5-be4006a38a1d
    type: regular
    task:
      id: cd560420-a769-4cbf-83c5-be4006a38a1d
      version: -1
      name: Get user rate limit
      description: Get rate limit for a specific user name. ThreatGrid employs a simple
        rate limiting method for sample submissions by specifying the number of samples
        which can be submitted within some variable time period by a user. Multiple
        rate limits can be employed to form overlapping submission limits. For example,
        20 submissions per hour AND 400 per day.
      script: Threat Grid New|||threat-grid-user-get-rate-limit
      type: regular
      iscommand: true
      brand: Threat Grid New
    scriptarguments:
      login:
        simple: ${ThreatGrid.User.Login}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 7254d3e8-74c0-47c1-8959-43d7f733dfc1
    type: regular
    task:
      id: 7254d3e8-74c0-47c1-8959-43d7f733dfc1
      version: -1
      name: 'Download the sample '
      description: Download a sample by using its ID. The downloaded file is an archive
        of the sample itself, in a zip format as a form of quarantine.
      script: Threat Grid New|||threat-grid-download-sample-by-id
      type: regular
      iscommand: true
      brand: Threat Grid New
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      id:
        simple: ${ThreatGrid.Sample.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 6bc6edee-72c4-4a28-8e79-eea0fa34fe26
    type: regular
    task:
      id: 6bc6edee-72c4-4a28-8e79-eea0fa34fe26
      version: -1
      name: Reupload the sample
      description: Submits a sample to threat grid for analysis
      script: Threat Grid New|||threat-grid-upload-sample
      type: regular
      iscommand: true
      brand: Threat Grid New
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      file-id:
        simple: ${File.EntryID}
      filename:
        simple: SampleTestFile
      playbook: {}
      private: {}
      tags: {}
      vm: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
    note: false
  "9":
    id: "9"
    taskid: c4647362-3a99-4e47-8e7c-2d2cfaf821e2
    type: regular
    task:
      id: c4647362-3a99-4e47-8e7c-2d2cfaf821e2
      version: -1
      name: Sleep until analysis is done
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "300"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 2f58788e-b4ee-426a-8a0a-e574725c7dbe
    type: regular
    task:
      id: 2f58788e-b4ee-426a-8a0a-e574725c7dbe
      version: -1
      name: threat-grid-organization-get-rate-limit
      description: Get rate limits applied to an organization. ThreatGrid employs
        a simple rate limiting method for sample submissions by specifying the number
        of samples which can be submitted within some variable time period by an entire
        organization and/or per a license basis. Multiple rate limits can be employed
        to form overlapping submission limits. For example, 20 submissions per hour
        AND 400 per day.
      script: Threat Grid New|||threat-grid-organization-get-rate-limit
      type: regular
      iscommand: true
      brand: Threat Grid New
    scriptarguments:
      adminLogin:
        simple: ${ThreatGrid.User.Login}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
  "11":
    id: "11"
    taskid: c5b7c3c1-dc78-4bbd-83bc-b08fda50ab07
    type: condition
    task:
      id: c5b7c3c1-dc78-4bbd-83bc-b08fda50ab07
      version: -1
      name: Check if user is admin
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    scriptarguments:
      left:
        simple: ${ThreatGrid.User.Role}
      right:
        simple: org-admin
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 7fc9d00b-f1e5-4c54-88ed-bc8608c6fa4a
    type: condition
    task:
      id: 7fc9d00b-f1e5-4c54-88ed-bc8608c6fa4a
      version: -1
      name: Verify that the sample state is succ
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "14"
      "yes":
      - "15"
    scriptarguments:
      value:
        simple: ${ThreatGrid.Sample.State(val=='succ')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 57b56836-6d41-49c1-85aa-35ed78ec95ba
    type: regular
    task:
      id: 57b56836-6d41-49c1-85aa-35ed78ec95ba
      version: -1
      name: Sleep until analysis is done
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      seconds:
        simple: "300"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 797.5,
          "y": 1245
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 06705e4b-663c-4e20-8cd5-4856ecbf57cc
    type: regular
    task:
      id: 06705e4b-663c-4e20-8cd5-4856ecbf57cc
      version: -1
      name: threat-grid-get-threat-summary-by-id
      description: Returns a summary of the threats detected during analysis
      script: Threat Grid New|||threat-grid-get-threat-summary-by-id
      type: regular
      iscommand: true
      brand: Threat Grid New
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      id:
        simple: ${ThreatGrid.Sample.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1595
        }
      }
    note: false
  "16":
    id: "16"
    taskid: 4975b612-35c9-4d68-81ca-aea41be1e84e
    type: condition
    task:
      id: 4975b612-35c9-4d68-81ca-aea41be1e84e
      version: -1
      name: Check we have a score for this file
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    scriptarguments:
      value:
        simple: ${ThreatGrid.Sample.Score}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1770
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 07971c4a-ae93-4156-8bda-67147d1e139d
    type: regular
    task:
      id: 07971c4a-ae93-4156-8bda-67147d1e139d
      version: -1
      name: closeInvestigation
      description: Close the current investigation
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      duplicates: {}
      id: {}
      internalemail: {}
      killchain: {}
      lob: {}
      outcome: {}
      phishingjoshtest: {}
      shiftnotes: {}
      syfintenralid: {}
      testarr: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1945
        }
      }
    note: false
  "18":
    id: "18"
    taskid: b17ad7fa-84da-4da9-86fe-129c4db96bac
    type: condition
    task:
      id: b17ad7fa-84da-4da9-86fe-129c4db96bac
      version: -1
      name: Verify that the sample state is succ
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    scriptarguments:
      value:
        simple: ${ThreatGrid.Sample.State(val=='succ')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 797.5,
          "y": 1420
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1990,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
