id: Test Playbook McAfee ePO
version: -1
name: Test Playbook McAfee ePO
description: Test the McAfee ePO integration by running basic commands
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f321cc54-abd1-4ba4-89d3-32c83b9c058e
    type: start
    task:
      id: f321cc54-abd1-4ba4-89d3-32c83b9c058e
      version: -1
      name: ""
      description: "-"
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: c43eb35c-006b-43fd-826b-c226be6dd05a
    type: regular
    task:
      id: c43eb35c-006b-43fd-826b-c226be6dd05a
      version: -1
      name: epo-help
      description: print help on ePO commands
      script: epo|||epo-help
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      command: {}
      search:
        simple: agent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
  "2":
    id: "2"
    taskid: bd751652-ad82-479c-8e46-663164e2c0a0
    type: regular
    task:
      id: bd751652-ad82-479c-8e46-663164e2c0a0
      version: -1
      name: epo-get-current-dat
      description: Check the existing DAT file version in ePO
      script: epo|||epo-get-current-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 71271cf6-80e5-435e-844a-d88a1eb977a1
    type: regular
    task:
      id: 71271cf6-80e5-435e-844a-d88a1eb977a1
      version: -1
      name: epo-get-latest-dat
      description: Check the latest DAT file in McAfee repository
      script: epo|||epo-get-latest-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 131e04b8-503b-4157-83a4-9452fc62671c
    type: regular
    task:
      id: 131e04b8-503b-4157-83a4-9452fc62671c
      version: -1
      name: epo-get-system-tree-group
      description: Get System Tree groups
      script: epo|||epo-get-system-tree-group
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      search: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
  "5":
    id: "5"
    taskid: d5b711a6-8243-46b0-84d5-9b8cbba6ba94
    type: title
    task:
      id: d5b711a6-8243-46b0-84d5-9b8cbba6ba94
      version: -1
      name: Done
      description: "-"
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
  "6":
    id: "6"
    taskid: d6b1af86-4ee6-41dc-887b-8b21d9198092
    type: regular
    task:
      id: d6b1af86-4ee6-41dc-887b-8b21d9198092
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 5874dc1d-57bc-4d27-8768-20c40805b282
    type: regular
    task:
      id: 5874dc1d-57bc-4d27-8768-20c40805b282
      version: -1
      name: epo-update-client-dat
      description: Run client task to update the DAT file
      script: epo|||epo-update-client-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      abortAfterMinutes: {}
      randomizationInterval: {}
      retryAttempts: {}
      retryIntervalInSeconds: {}
      stopAfterMinutes: {}
      systems:
        simple: ADMIN-PC
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 6da4c4bd-a79a-415f-8d03-e04cb4780693
    type: regular
    task:
      id: 6da4c4bd-a79a-415f-8d03-e04cb4780693
      version: -1
      name: epo-update-repository
      description: Trigger a Server Task in specific ePO servers to pull latest signatures
        from update server
      script: epo|||epo-update-repository
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
  "12":
    id: "12"
    taskid: eda8855e-4f13-41e6-8a0d-6e4468f802d0
    type: regular
    task:
      id: eda8855e-4f13-41e6-8a0d-6e4468f802d0
      version: -1
      name: epo-find-systems
      description: Find systems in the System Tree - by group ID or by search
      script: epo|||epo-find-systems
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      groupId:
        simple: "5"
      verbose: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "16":
    id: "16"
    taskid: ad83e30f-9ae6-4189-8f97-f27563a865f6
    type: condition
    task:
      id: ad83e30f-9ae6-4189-8f97-f27563a865f6
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      left:
        complex:
          root: McAfee
          filters:
          - - operator: isEqualNumber
              left:
                value:
                  simple: McAfee.ePO.SystemTreeGroups.groupId
                iscontext: true
              right:
                value:
                  simple: "5"
          accessor: ePO.SystemTreeGroups.groupId
      right:
        simple: "5"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 371fdf2e-154b-44a5-81d7-4db6197fdf61
    type: condition
    task:
      id: 371fdf2e-154b-44a5-81d7-4db6197fdf61
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    scriptarguments:
      left:
        complex:
          root: McAfee
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: McAfee.ePO.Endpoint.Hostname
                iscontext: true
              right:
                value:
                  simple: mar
          accessor: ePO.Endpoint.IPAddress
      right:
        simple: 192.168.1.103
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
  "18":
    id: "18"
    taskid: 427cf98f-2058-4cde-8daa-89b63fa04d72
    type: regular
    task:
      id: 427cf98f-2058-4cde-8daa-89b63fa04d72
      version: -1
      name: epo-advanced-command
      description: 'Execute ePO command. Run ''epo-help'' command to see a list available
        commands. e.g:  !epo-advanced-command command="clienttask.find" commandArgs="searchText:On-demand".
        You can also specify ''headers'' argument  to filter tables headers. e.g:
        ''!epo-command command=system.find searchText=10.0.0.1 headers=EPOBranchNode.AutoID,EPOComputerProperties.ComputerName''. '
      script: epo|||epo-advanced-command
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      command:
        simple: clienttask.find
      commandArgs:
        simple: searchText:On-demand
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []